### ISSUE TITLE
There is a error in your code

### ISSUE THREAD

**Issue by qiang92** [shaohua0116/WGAN-GP-TensorFlow#1]
Line 36 in generator.py file.
origin
` _ = fc(_, self.start_dim_x * self.start_dim_y  * self.start_dim_ch,`

should be
` _ = fc(input, self.start_dim_x * self.start_dim_y  * self.start_dim_ch,`

**Comment by shaohua0116** [comment]
Thanks for pointing this out. I fixed it and pushed the code.
